export const level40 = [
  // --- LEVEL 40: INTRO TO .map() (1–100) ---
  // Basic number mapping (increment, double, etc.) (1–20)

  `[1, 2, 3].map(n => n + 1);`,
  `[4, 5].map(n => n * 2);`,
  `[2, 6, 8].map(n => n - 1);`,
  `[10, 20].map(n => n / 2);`,
  `[3, 3, 3].map(n => n * 3);`,
  `[5, 1].map(n => n + 10);`,
  `[9, 8, 7].map(n => n - 2);`,
  `[2, 4, 6].map(n => n * n);`,
  `[1, 5].map(n => n * 5);`,
  `[7, 2].map(n => n + 3);`,
  `[6, 6, 6].map(n => n / 3);`,
  `[8, 1].map(n => n * 4);`,
  `[9, 3].map(n => n - 1);`,
  `[2, 2, 2].map(n => n + 2);`,
  `[10, 5].map(n => n / 5);`,
  `[3, 9].map(n => n * 2);`,
  `[4, 4].map(n => n + 4);`,
  `[5, 10].map(n => n - 3);`,
  `[7, 14].map(n => n / 7);`,
  `[6, 2].map(n => n * 10);`,

  // Mapping strings (to upper, lower, adding text) (21–40)

  `["hi", "there"].map(s => s.toUpperCase());`,
  `["Dog", "Cat"].map(s => s.toLowerCase());`,
  `["{{name}}", "Alex"].map(s => s + "!");`,
  `["A", "B"].map(s => s + s);`,
  `["hello"].map(s => s.toUpperCase());`,
  `["sun", "moon"].map(s => s + " light");`,
  `["Car", "Bike"].map(s => s.toLowerCase());`,
  `["JS", "Code"].map(s => s + "!" );`,
  `["Tree", "Rock"].map(s => s.toUpperCase());`,
  `["{{city}}", "Paris"].map(s => s + " City");`,
  `["good", "day"].map(s => s + "?");`,
  `["Cat"].map(s => s + "nip");`,
  `["sky", "cloud"].map(s => s.toUpperCase());`,
  `["yes", "no"].map(s => s + "!");`,
  `["blue", "red"].map(s => s + " color");`,
  `["home", "away"].map(s => s.toUpperCase());`,
  `["up", "down"].map(s => s + "_test");`,
  `["{{country}}", "USA"].map(s => s.toUpperCase());`,
  `["bird", "dog"].map(s => s + "s");`,
  `["code"].map(s => s.toUpperCase());`,

  // Extracting properties from objects (41–60)

  `[{ age: 10 }, { age: 5 }].map(p => p.age);`,
  `[{ age: {{age}} }, { age: 2 }].map(o => o.age);`,
  `[{ name: "{{name}}" }, { name: "Bob" }].map(o => o.name);`,
  `[{ city: "{{city}}" }, { city: "Rome" }].map(o => o.city);`,
  `[{ job: "{{job}}" }, { job: "Pilot" }].map(o => o.job);`,
  `[{ n: 1 }, { n: 2 }].map(o => o.n);`,
  `[{ x: 9 }, { x: 3 }].map(o => o.x);`,
  `[{ id: 5 }, { id: 10 }].map(o => o.id);`,
  `[{ country: "{{country}}" }, { country: "Japan" }].map(o => o.country);`,
  `[{ value: 100 }, { value: 50 }].map(o => o.value);`,
  `[{ age: 4 }, { age: 9 }].map(o => o.age);`,
  `[{ n: 7 }, { n: 8 }].map(o => o.n);`,
  `[{ score: 10 }, { score: 20 }].map(o => o.score);`,
  `[{ size: "L" }, { size: "M" }].map(o => o.size);`,
  `[{ temp: 30 }, { temp: 20 }].map(o => o.temp);`,
  `[{ name: "Sam" }, { name: "{{name}}" }].map(o => o.name);`,
  `[{ city: "Berlin" }, { city: "{{city}}" }].map(o => o.city);`,
  `[{ a: 1 }, { a: 3 }].map(o => o.a);`,
  `[{ height: 180 }, { height: 150 }].map(o => o.height);`,
  `[{ brand: "Apple" }, { brand: "Samsung" }].map(o => o.brand);`,

  // Transforming objects → new objects (61–80)

  `[{ age: 10 }, { age: 5 }].map(o => ({ value: o.age }));`,
  `[{ name: "{{name}}" }, { name: "Bob" }].map(o => ({ label: o.name }));`,
  `[{ city: "{{city}}" }, { city: "Tokyo" }].map(o => ({ location: o.city }));`,
  `[{ n: 2 }, { n: 4 }].map(o => ({ double: o.n * 2 }));`,
  `[{ x: 3 }, { x: 6 }].map(o => ({ squared: o.x * o.x }));`,
  `[{ age: 1 }, { age: 2 }].map(o => ({ plusOne: o.age + 1 }));`,
  `[{ score: 10 }, { score: 20 }].map(o => ({ half: o.score / 2 }));`,
  `[{ num: 5 }, { num: 8 }].map(o => ({ triple: o.num * 3 }));`,
  `[{ level: 1 }, { level: 2 }].map(o => ({ next: o.level + 1 }));`,
  `[{ name: "Sam" }, { name: "{{name}}" }].map(o => ({ shout: o.name.toUpperCase() }));`,
  `[{ city: "LA" }, { city: "{{city}}" }].map(o => ({ tag: "City: " + o.city }));`,
  `[{ a: 4 }, { a: 7 }].map(o => ({ minus: o.a - 1 }));`,
  `[{ x: 10 }, { x: 12 }].map(o => ({ divided: o.x / 2 }));`,
  `[{ value: 3 }, { value: 6 }].map(o => ({ plusFive: o.value + 5 }));`,
  `[{ age: 8 }, { age: 9 }].map(o => ({ doubled: o.age * 2 }));`,
  `[{ num: 1 }, { num: 5 }].map(o => ({ negated: -o.num }));`,
  `[{ length: 10 }, { length: 5 }].map(o => ({ total: o.length + 10 }));`,
  `[{ count: 3 }, { count: 6 }].map(o => ({ squared: o.count ** 2 }));`,
  `[{ weight: 50 }, { weight: 100 }].map(o => ({ half: o.weight / 2 }));`,
  `[{ temp: 20 }, { temp: 30 }].map(o => ({ increased: o.temp + 3 }));`,

  // Mixed advanced (81–100)

  `[1, 2, 3].map(n => n * n);`,
  `["a", "b"].map(s => s.toUpperCase());`,
  `[5, 10].map(n => n - 5);`,
  `["{{name}}"].map(s => s + "!");`,
  `[10, 20, 30].map(n => n / 10);`,
  `["x", "y", "z"].map(s => s + s);`,
  `[2, 4].map(n => n ** 3);`,
  `["hi"].map(s => s.repeat(2));`,
  `[{ age: 3 }].map(o => o.age + 7);`,
  `[9, 3].map(n => n * 2);`,
  `["sun"].map(s => s.toUpperCase());`,
  `[100, 50].map(n => n / 25);`,
  `["cat", "dog"].map(s => s + "!");`,
  `[{ name: "{{name}}" }].map(o => o.name + "!");`,
  `[7, 14].map(n => n / 7);`,
  `["A"].map(s => s + "A");`,
  `[8, 1].map(n => n * 4);`,
  `["{{city}}"].map(s => s + " City");`,
  `[2, 3, 4].map(n => n + 10);`,
  `["ok"].map(s => s.toUpperCase());`,
];
