export const level41 = [
  // --- LEVEL 41: INTRO TO .filter() (1–100) ---
  // Filtering numbers (keep even, odd, >, <) (1–20)

  `[1, 2, 3, 4].filter(n => n % 2 === 0);`,
  `[5, 6, 7, 8].filter(n => n % 2 !== 0);`,
  `[10, 20, 5].filter(n => n > 10);`,
  `[3, 9, 12].filter(n => n < 10);`,
  `[2, 4, 6, 8].filter(n => n > 4);`,
  `[1, 5, 10].filter(n => n >= 5);`,
  `[7, 14, 21].filter(n => n % 7 === 0);`,
  `[1, 2, 3].filter(n => n !== 2);`,
  `[9, 3, 6].filter(n => n < 6);`,
  `[4, 8, 12].filter(n => n / 4 === 2);`,
  `[2, 3, 4, 5].filter(n => n % 2 === 1);`,
  `[10, 15, 20].filter(n => n % 5 === 0);`,
  `[3, 6, 9].filter(n => n > 5);`,
  `[8, 2, 1].filter(n => n < 3);`,
  `[12, 24, 36].filter(n => n > 20);`,
  `[5, 10, 15].filter(n => n >= 10);`,
  `[7, 11, 13].filter(n => n > 10);`,
  `[1, 4, 7].filter(n => n <= 4);`,
  `[2, 6, 10].filter(n => n % 2 === 0);`,
  `[9, 18, 27].filter(n => n / 9 === 2);`,

  // Filtering strings by length, letters, etc. (21–40)

  `["apple", "hi", "cat"].filter(s => s.length > 3);`,
  `["dog", "car", "sun"].filter(s => s.startsWith("c"));`,
  `["{{name}}", "Sam"].filter(s => s.length < 5);`,
  `["Berlin", "LA"].filter(s => s.length > 3);`,
  `["ant", "bee", "cow"].filter(s => s.endsWith("e"));`,
  `["hi", "hello"].filter(s => s.includes("h"));`,
  `["red", "blue"].filter(s => s.length === 3);`,
  `["{{city}}", "Rome"].filter(s => s !== "Rome");`,
  `["sun", "moon"].filter(s => s[0] === "m");`,
  `["car", "bike", "bus"].filter(s => s.length > 3);`,
  `["alpha", "beta"].filter(s => s.includes("a"));`,
  `["one", "two"].filter(s => s.length < 3);`,
  `["A", "B", "C"].filter(s => s === "A");`,
  `["rock", "tree"].filter(s => s.startsWith("t"));`,
  `["sky", "cloud"].filter(s => s.length > 3);`,
  `["yes", "no"].filter(s => s === "yes");`,
  `["cat", "dog"].filter(s => s !== "dog");`,
  `["apple", "pear"].filter(s => s.includes("p"));`,
  `["{{country}}", "USA"].filter(s => s.length > 3);`,
  `["house", "car"].filter(s => s.length === 5);`,

  // Filtering objects by number property (41–60)

  `[{ age: 10 }, { age: 5 }].filter(o => o.age > 6);`,
  `[{ age: {{age}} }, { age: 3 }].filter(o => o.age < 10);`,
  `[{ age: 20 }, { age: 30 }].filter(o => o.age >= 25);`,
  `[{ age: 1 }, { age: 9 }].filter(o => o.age === 9);`,
  `[{ age: 4 }, { age: 12 }].filter(o => o.age > 5);`,
  `[{ score: 10 }, { score: 2 }].filter(o => o.score > 5);`,
  `[{ value: 100 }, { value: 50 }].filter(o => o.value === 100);`,
  `[{ x: 3 }, { x: 6 }].filter(o => o.x % 3 === 0);`,
  `[{ n: 2 }, { n: 5 }].filter(o => o.n < 4);`,
  `[{ temp: 30 }, { temp: 20 }].filter(o => o.temp > 25);`,
  `[{ age: 18 }, { age: 22 }].filter(o => o.age >= 20);`,
  `[{ score: 7 }, { score: 7 }].filter(o => o.score === 7);`,
  `[{ id: 1 }, { id: 2 }].filter(o => o.id !== 1);`,
  `[{ level: 3 }, { level: 1 }].filter(o => o.level > 1);`,
  `[{ count: 5 }, { count: 2 }].filter(o => o.count < 5);`,
  `[{ a: 10 }, { a: 4 }].filter(o => o.a > 4);`,
  `[{ age: 8 }, { age: 12 }].filter(o => o.age <= 10);`,
  `[{ num: 3 }, { num: 9 }].filter(o => o.num % 3 === 0);`,
  `[{ value: 1 }, { value: 0 }].filter(o => o.value === 1);`,
  `[{ x: 7 }, { x: 14 }].filter(o => o.x > 10);`,

  // Filtering objects by string property (61–80)

  `[{ name: "Sam" }, { name: "{{name}}" }].filter(o => o.name.length < 4);`,
  `[{ city: "{{city}}" }, { city: "Paris" }].filter(o => o.city === "Paris");`,
  `[{ job: "{{job}}" }, { job: "Pilot" }].filter(o => o.job !== "Pilot");`,
  `[{ country: "{{country}}" }, { country: "Japan" }].filter(o => o.country.includes("a"));`,
  `[{ name: "Alex" }, { name: "Bob" }].filter(o => o.name.startsWith("A"));`,
  `[{ pet: "Dog" }, { pet: "Cat" }].filter(o => o.pet === "Dog");`,
  `[{ car: "BMW" }, { car: "Audi" }].filter(o => o.car === "Audi");`,
  `[{ fruit: "Apple" }, { fruit: "Pear" }].filter(o => o.fruit.length > 4);`,
  `[{ brand: "Nike" }, { brand: "Puma" }].filter(o => o.brand.includes("u"));`,
  `[{ hero: "Batman" }, { hero: "Flash" }].filter(o => o.hero.endsWith("n"));`,
  `[{ color: "Red" }, { color: "Blue" }].filter(o => o.color === "Blue");`,
  `[{ title: "Hello" }, { title: "Hi" }].filter(o => o.title.length > 2);`,
  `[{ city: "Rome" }, { city: "LA" }].filter(o => o.city !== "LA");`,
  `[{ name: "{{name}}" }, { name: "Sam" }].filter(o => o.name.length >= 3);`,
  `[{ place: "Park" }, { place: "Mall" }].filter(o => o.place.startsWith("P"));`,
  `[{ lang: "JS" }, { lang: "Python" }].filter(o => o.lang.length > 2);`,
  `[{ food: "Pizza" }, { food: "Tea" }].filter(o => o.food !== "Tea");`,
  `[{ mode: "Auto" }, { mode: "Manual" }].filter(o => o.mode.includes("a"));`,
  `[{ car: "Tesla" }, { car: "Ford" }].filter(o => o.car.startsWith("T"));`,
  `[{ animal: "Zebra" }, { animal: "Ant" }].filter(o => o.animal.length > 3);`,

  // Mixed advanced (81–100)

  `[1, 2, 3].filter(n => n > 1);`,
  `["a", "b", "c"].filter(s => s !== "b");`,
  `[10, 5, 0].filter(n => n);`,
  `["{{name}}", "Alex"].filter(s => s !== "Alex");`,
  `[{ age: 5 }, { age: 10 }].filter(o => o.age > 5);`,
  `[9, 3, 6].filter(n => n % 3 === 0);`,
  `["sun", "star"].filter(s => s.length === 3);`,
  `[2, 4, 6, 8].filter(n => n < 7);`,
  `[{ x: 1 }, { x: 2 }].filter(o => o.x === 2);`,
  `["yes", "no"].filter(s => s === "yes");`,
  `[100, 50, 25].filter(n => n >= 50);`,
  `["tree", "rock"].filter(s => s.includes("e"));`,
  `[{ city: "{{city}}" }].filter(o => o.city.length > 3);`,
  `[5, 10, 15].filter(n => n % 5 === 0);`,
  `["A", "AA"].filter(s => s.length > 1);`,
  `[8, 1].filter(n => n > 2);`,
  `["{{country}}"].filter(s => s.includes("a"));`,
  `[2, 3, 4].filter(n => n + 1 === 3);`,
  `["ok", "yes"].filter(s => s.toUpperCase() === "OK");`,
  `[9, 18, 27].filter(n => n / 9 === 3);`,
];
