export const level46 = [
  // --- LEVEL 46: MINI LOGIC CHALLENGES (1–100) ---

  // Simple string logic (1–20)

  `"{{name}}".toUpperCase();`,
  `"{{city}}".slice(0, 3);`,
  `"hello".includes("e");`,
  `"cold".replace("c", "b");`,
  `"cat".repeat(2);`,
  `"{{country}}".length;`,
  `"apple"[0];`,
  `"sun" + "light";`,
  `"car".toUpperCase();`,
  `"blue".toLowerCase();`,
  `"dog".includes("o");`,
  `"red".repeat(3);`,
  `"note".slice(1);`,
  `"walk".includes("l");`,
  `"tree"[2];`,
  `"code" + " practice";`,
  `"sky".length;`,
  `"house".slice(0, 2);`,
  `"job: {{job}}";`,
  `"hello".charAt(1);`,

  // Array access & basics (21–40)

  `[1,2,3][0];`,
  `["a","b","c"][2];`,
  `[5,10,15].length;`,
  `["x","y","z"].includes("y");`,
  `["red","blue"].concat(["green"]);`,
  `[10,20,30].indexOf(20);`,
  `["cat","dog"].join("-");`,
  `[2,4,6].map(n => n / 2);`,
  `["a","b"].reverse();`,
  `["sun","moon"].includes("sun");`,
  `["{{city}}","Paris"][[1]];`,
  `[3,6,9].filter(n => n > 5);`,
  `["hi","hello"].map(w => w.length);`,
  `[1,5,10].filter(n => n < 7);`,
  `["dog","cat"][1].toUpperCase();`,
  `["x","y","z"].map(ch => ch + "!");`,
  `[4,8,12].map(n => n / 4);`,
  `["A","B"].includes("C");`,
  `[true,false,true].filter(b => b);`,
  `["lake","river"].map(w => w.length);`,

  // Quick math logic (41–60)

  `5 + 3;`,
  `10 - 4;`,
  `3 * 3;`,
  `12 / 3;`,
  `9 % 2;`,
  `2 ** 3;`,
  `Math.max(2, 9);`,
  `Math.min(4, 1);`,
  `Math.abs(-7);`,
  `(5 + 5) / 2;`,
  `{{age}} + 10;`,
  `({{age}} * 2) - 3;`,
  `Math.sqrt(16);`,
  `10 % 4;`,
  `7 + (3 * 2);`,
  `20 / (5 - 3);`,
  `(2 + 2) * (3 + 1);`,
  `100 / 10;`,
  `8 * (2 + 1);`,
  `30 - (10 + 5);`,

  // Reduce, map, filter mixed short tasks (61–80)

  `[1,2,3].reduce((t,n) => t + n, 0);`,
  `["a","b"].reduce((s,c) => s + c, "");`,
  `[5,10].map(n => n * 2);`,
  `[7,14,21].filter(n => n > 10);`,
  `["cat","cow"].filter(w => w.includes("c"));`,
  `[1,2,3].map(n => n + 1);`,
  `["hi","hey"].map(w => w.toUpperCase());`,
  `[10,20,30].reduce((t,n) => t + n, 0);`,
  `["sun","sky"].map(w => w.length);`,
  `[2,4,6].filter(n => n % 4 === 0);`,
  `[true,false,true].filter(b => b);`,
  `["red","blue"].map(c => c + "!");`,
  `[3,6,9].map(n => n / 3);`,
  `["{{name}}","Alex"].filter(n => n.length > 3);`,
  `[1,3,5].map(n => n * 10);`,
  `["a","b","c"].reduce((s,c) => s + c, "");`,
  `[8,4].map(n => n / 2);`,
  `["car","bike"].filter(v => v.includes("a"));`,
  `[7,14].map(n => n + 1);`,
  `[2,5,8].filter(n => n > 4);`,

  // Quick function-based tasks (81–100)

  `function greet(n){ return "Hello " + n } greet("{{name}}");`,
  `function double(x){ return x * 2 } double(5);`,
  `function sayHi(){ return "Hi" } sayHi();`,
  `function first(arr){ return arr[0] } first(["a","b"]);`,
  `function upper(w){ return w.toUpperCase() } upper("hello");`,
  `function add(a,b){ return a + b } add(3,4);`,
  `function last(arr){ return arr[arr.length-1] } last([1,2,3]);`,
  `function city(){ return "{{city}}" } city();`,
  `function area(a,b){ return a*b } area(3,4);`,
  `function intro(n,c){ return n + " from " + c } intro("{{name}}","{{city}}");`,
  `function isBig(n){ return n > 10 } isBig(12);`,
  `function firstChar(s){ return s[0] } firstChar("test");`,
  `function square(x){ return x * x } square(6);`,
  `function len(s){ return s.length } len("hello");`,
  `function wrap(x){ return "["+x+"]" } wrap("ok");`,
  `function bold(w){ return "<b>"+w+"</b>" } bold("hi");`,
  `function repeat(w){ return w.repeat(2) } repeat("go");`,
  `function isEven(n){ return n % 2 === 0 } isEven(4);`,
  `function full(n,a){ return n + " (" + a + ")" } full("{{name}}", {{age}});`,
  `function tag(w){ return w + "_tag" } tag("code");`,
];
