export const level48 = [
  // --- LEVEL 48: COMPLETE THE FUNCTION RETURN (1–100) ---

  // Basic string transforms (1–20)

  `function makeUpper(w) { return w.toUpperCase(); }`,
  `function firstChar(s) { return s[0]; }`,
  `function lastChar(s) { return s[s.length - 1]; }`,
  `function addBang(w) { return w + "!"; }`,
  `function greet(n) { return "Hello " + n; }`,
  `function cityLabel(c) { return "City: " + c; }`,
  `function repeatTwice(w) { return w.repeat(2); }`,
  `function lower(w) { return w.toLowerCase(); }`,
  `function tag(w) { return w + "_tag"; }`,
  `function wrap(x) { return "[" + x + "]"; }`,
  `function wordLen(w) { return w.length; }`,
  `function slice2(w) { return w.slice(0,2); }`,
  `function end2(w) { return w.slice(-2); }`,
  `function sayHi() { return "Hi"; }`,
  `function jobLabel(j) { return "Job: " + j; }`,
  `function countryLine(c) { return "From " + c; }`,
  `function echo(x) { return x; }`,
  `function makeTitle(w) { return w.toUpperCase(); }`,
  `function joinWords(a,b) { return a + " " + b; }`,
  `function codeLine(w) { return w + " code"; }`,

  // Arrays — simple outputs (21–40)

  `function first(arr) { return arr[0]; }`,
  `function last(arr) { return arr[arr.length - 1]; }`,
  `function len(arr) { return arr.length; }`,
  `function upperAll(arr) { return arr.map(w => w.toUpperCase()); }`,
  `function doubleAll(arr) { return arr.map(n => n * 2); }`,
  `function evens(arr) { return arr.filter(n => n % 2 === 0); }`,
  `function odds(arr) { return arr.filter(n => n % 2 !== 0); }`,
  `function sum(arr) { return arr.reduce((t,n)=>t+n,0); }`,
  `function initials(arr) { return arr.map(w => w[0]); }`,
  `function lengths(arr) { return arr.map(w => w.length); }`,
  `function plusOne(arr) { return arr.map(n => n+1); }`,
  `function onlyLong(arr) { return arr.filter(w => w.length > 3); }`,
  `function firstTwo(arr) { return arr.slice(0,2); }`,
  `function lastTwo(arr) { return arr.slice(-2); }`,
  `function reverse(arr) { return arr.reverse(); }`,
  `function containsA(arr) { return arr.filter(w => w.includes("a")); }`,
  `function squares(arr) { return arr.map(n => n*n); }`,
  `function doubles(arr) { return arr.map(n => n*2); }`,
  `function addEx(arr) { return arr.map(w => w + "!"); }`,
  `function onlyBig(arr) { return arr.filter(n => n > 10); }`,

  // Numbers — transforms (41–60)

  `function double(n) { return n * 2; }`,
  `function triple(n) { return n * 3; }`,
  `function square(n) { return n * n; }`,
  `function cube(n) { return n * n * n; }`,
  `function plusTen(n) { return n + 10; }`,
  `function minusFive(n) { return n - 5; }`,
  `function half(n) { return n / 2; }`,
  `function tenMore(n) { return n + 10; }`,
  `function timesFour(n) { return n * 4; }`,
  `function absVal(n) { return Math.abs(n); }`,
  `function isEven(n) { return n % 2 === 0; }`,
  `function isOdd(n) { return n % 2 !== 0; }`,
  `function bigger(a,b) { return Math.max(a,b); }`,
  `function smaller(a,b) { return Math.min(a,b); }`,
  `function add(a,b) { return a + b; }`,
  `function subtract(a,b) { return a - b; }`,
  `function multiply(a,b) { return a * b; }`,
  `function divide(a,b) { return a / b; }`,
  `function mod(a,b) { return a % b; }`,
  `function avg(a,b) { return (a + b) / 2; }`,

  // Mini real-life transforms (61–80)

  `function fullName(a,b) { return a + " " + b; }`,
  `function intro(n,c) { return n + " from " + c; }`,
  `function ageLine(a) { return "Age: " + a; }`,
  `function tempC(c) { return c + "°C"; }`,
  `function tempF(f) { return f + "°F"; }`,
  `function username(n) { return n.toLowerCase() + "_01"; }`,
  `function hashtag(w) { return "#" + w; }`,
  `function product(a,b) { return a * b; }`,
  `function metersToCm(m) { return m*100; }`,
  `function kmToM(k) { return k*1000; }`,
  `function greetCity(c) { return "Welcome to " + c; }`,
  `function logLine(x) { return "Log: " + x; }`,
  `function idLine(n) { return "ID-" + n; }`,
  `function scorePlus(s) { return s + 5; }`,
  `function rating(r) { return r + "/10"; }`,
  `function price(p) { return "$" + p; }`,
  `function percent(n) { return n + "%"; }`,
  `function email(n) { return n + "@mail.com"; }`,
  `function title(w) { return w.toUpperCase(); }`,
  `function flag(c) { return c + " 🇨🇭"; }`,

  // Slightly more advanced patterns (81–100)

  `function clean(s) { return s.trim(); }`,
  `function noSpaces(s) { return s.replace(/\\s+/g, ""); }`,
  `function toList(a,b) { return [a,b]; }`,
  `function join3(a,b,c) { return a + "-" + b + "-" + c; }`,
  `function pick2(arr) { return arr.slice(0,2); }`,
  `function last3(arr) { return arr.slice(-3); }`,
  `function sum3(a,b,c) { return a + b + c; }`,
  `function max3(a,b,c) { return Math.max(a,b,c); }`,
  `function min3(a,b,c) { return Math.min(a,b,c); }`,
  `function upper2(a,b) { return a.toUpperCase() + " " + b.toUpperCase(); }`,
  `function concatArr(a,b) { return a.concat(b); }`,
  `function startsA(w) { return w.startsWith("a"); }`,
  `function endsX(w) { return w.endsWith("x"); }`,
  `function firstTwoChars(w) { return w.slice(0,2); }`,
  `function lastTwoChars(w) { return w.slice(-2); }`,
  `function prop(obj,p) { return obj[p]; }`,
  `function count(arr) { return arr.length; }`,
  `function doubleList(arr) { return arr.map(n=>n*2); }`,
  `function shoutAll(arr) { return arr.map(w=>w+"!"); }`,
  `function onlyShort(arr) { return arr.filter(w=>w.length<4); }`,
];
