export const level43 = [
  // --- LEVEL 43: STRING → OUTPUT TRANSFORMATIONS USING .map() (1–100) ---

  // Simple formatting (1–20)

  `["{{name}}"].map(n => "Hello " + n);`,
  `["{{city}}"].map(c => c + " is beautiful");`,
  `["apple"].map(f => "Fruit: " + f);`,
  `["JS"].map(x => x + " language");`,
  `["car"].map(v => "Vehicle: " + v);`,
  `["{{country}}"].map(c => "Country: " + c);`,
  `["hello"].map(w => w.toUpperCase());`,
  `["sky"].map(s => s + " blue");`,
  `["dog"].map(p => "Pet: " + p);`,
  `["bike"].map(b => b + " ride");`,
  `["hello"].map(w => w + "!");`,
  `["summer"].map(s => "Season: " + s);`,
  `["tea"].map(d => d + " drink");`,
  `["code"].map(x => x + " practice");`,
  `["tree"].map(t => t + " leaf");`,
  `["ball"].map(b => "Toy: " + b);`,
  `["music"].map(m => m + " time");`,
  `["red"].map(c => c + " color");`,
  `["water"].map(w => w + " bottle");`,
  `["{{job}}"].map(j => "Job: " + j);`,

  // Mapping strings to lengths or parts (21–40)

  `["JavaScript"].map(s => s.length);`,
  `["hello"].map(s => s[0]);`,
  `["world"].map(s => s.slice(0, 3));`,
  `["coding"].map(s => s.length + 2);`,
  `["sunset"].map(s => s.toUpperCase());`,
  `["night"].map(s => s.toLowerCase());`,
  `["pizza"].map(s => s + " slice");`,
  `["blue"].map(s => s.repeat(2));`,
  `["{{name}}"].map(s => s.length);`,
  `["{{country}}"].map(s => s.slice(0, 2));`,
  `["apple"].map(s => s[1]);`,
  `["car"].map(s => s + s);`,
  `["rock"].map(s => s.slice(1));`,
  `["wave"].map(s => s + " sound");`,
  `["tree"].map(s => s.length * 2);`,
  `["air"].map(s => s + "!");`,
  `["sky"].map(s => s + "_sky");`,
  `["lion"].map(s => s.toUpperCase());`,
  `["wind"].map(s => s + " breeze");`,
  `["home"].map(s => s.length);`,

  // Mapping sentences (41–60)

  `["{{name}} loves coding"].map(t => t.toUpperCase());`,
  `["Welcome to {{city}}"].map(t => t + "!");`,
  `["The weather is warm"].map(t => t.length);`,
  `["Coding every day"].map(t => t + " helps");`,
  `["Practice makes perfect"].map(t => t.slice(0, 8));`,
  `["Hello world"].map(t => t.replace("world", "{{name}}"));`,
  `["Great day"].map(t => t + " indeed");`,
  `["Stay strong"].map(t => t.toUpperCase());`,
  `["Keep going"].map(t => t.length + 5);`,
  `["Good morning"].map(t => t + " sunshine");`,
  `["Happy coding"].map(t => t.toLowerCase());`,
  `["Try again"].map(t => t + "!");`,
  `["Almost there"].map(t => t.length);`,
  `["Finish strong"].map(t => t + " now");`,
  `["Be patient"].map(t => t.toUpperCase());`,
  `["Learning JS"].map(t => t + " daily");`,
  `["Stay focused"].map(t => t + "_mode");`,
  `["Just keep coding"].map(t => t[0]);`,
  `["Time to code"].map(t => t.replace("code", "practice"));`,
  `["Make progress"].map(t => t.length * 2);`,

  // Map with replacements and conversions (61–80)

  `["{{city}}"].map(s => s.replace(s, "City: " + s));`,
  `["{{country}}"].map(s => "From " + s);`,
  `["{{name}}"].map(s => "Name: " + s);`,
  `["child"].map(s => s + "hood");`,
  `["car"].map(s => s + " model");`,
  `["lake"].map(s => s + "_water");`,
  `["mountain"].map(s => s.length + 1);`,
  `["phone"].map(s => s[0] + "_device");`,
  `["walk"].map(s => s + " path");`,
  `["run"].map(s => s.toUpperCase());`,
  `["jump"].map(s => s + " high");`,
  `["swim"].map(s => s + " fast");`,
  `["read"].map(s => "Book: " + s);`,
  `["write"].map(s => "Text: " + s);`,
  `["draw"].map(s => "Art: " + s);`,
  `["look"].map(s => s + " around");`,
  `["learn"].map(s => s + " more");`,
  `["watch"].map(s => s.toLowerCase());`,
  `["study"].map(s => s + " daily");`,
  `["teach"].map(s => "Role: " + s);`,

  // Mixed transformations (81–100)

  `["blue"].map(s => s.toUpperCase());`,
  `["red"].map(s => s + "!");`,
  `["green"].map(s => s.length);`,
  `["tree"].map(s => s[2]);`,
  `["hello"].map(s => s.repeat(3));`,
  `["{{job}}"].map(j => j + " position");`,
  `["{{city}}"].map(c => c + "_area");`,
  `["world"].map(s => s.slice(1));`,
  `["map"].map(s => s.toUpperCase());`,
  `["code"].map(s => s + "_block");`,
  `["sky"].map(s => s + " view");`,
  `["day"].map(s => s.length + 2);`,
  `["night"].map(s => s.toLowerCase());`,
  `["road"].map(s => s + "_trip");`,
  `["lake"].map(s => s + " side");`,
  `["bird"].map(s => s.toUpperCase());`,
  `["cat"].map(s => s + "!");`,
  `["dog"].map(s => s.length);`,
  `["wave"].map(s => s + "_sound");`,
  `["stone"].map(s => s[0]);`,
];
