export const level47 = [
  // --- LEVEL 47: MINI CODE EVALUATION (1–100) ---

  // Basic strings (1–20)

  `"{{name}}".toUpperCase();`,
  `"{{city}}".toLowerCase();`,
  `"hello".slice(1);`,
  `"world"[2];`,
  `"abc".length;`,
  `"hi" + " there";`,
  `"sun".includes("u");`,
  `"tree".repeat(2);`,
  `"road".slice(0, 3);`,
  `"job: {{job}}";`,
  `"{{country}}".length;`,
  `"car".toUpperCase();`,
  `"code".replace("c","m");`,
  `"blue".includes("l");`,
  `"cat"[0];`,
  `"dog".repeat(3);`,
  `"lake".slice(2);`,
  `"sky".length + 2;`,
  `"hello".charAt(4);`,
  `"room".toLowerCase();`,

  // Arrays (21–40)

  `[1,2,3][1];`,
  `["a","b","c"].length;`,
  `[10,20,30].includes(20);`,
  `["red","blue"].join("-");`,
  `[5,10,15].map(n => n/5);`,
  `[3,6,9].filter(n => n > 5);`,
  `["hi","hey"].map(w => w.length);`,
  `[2,4,6][0] * 3;`,
  `["cat","dog"][1].toUpperCase();`,
  `[7,14,21].indexOf(21);`,
  `[1,3,5].map(n => n + 1);`,
  `[4,8].map(n => n / 2);`,
  `["sun","moon"].includes("sun");`,
  `[10,20,30].reduce((t,n)=>t+n,0);`,
  `["x","y","z"][2];`,
  `[2,5,8].filter(n => n % 2 === 0);`,
  `["{{city}}","Paris"][0];`,
  `[true,false,true].filter(b => b);`,
  `[3,6,9].map(n => n / 3);`,
  `["a","b","c"].reverse();`,

  // Math + expressions (41–60)

  `5 + 5;`,
  `8 - 3;`,
  `2 * 6;`,
  `12 / 3;`,
  `9 % 4;`,
  `2 ** 4;`,
  `Math.max(3,9);`,
  `Math.min(5,1);`,
  `Math.abs(-12);`,
  `(3 + 7) * 2;`,
  `({{age}} + 5);`,
  `({{age}} * 2) - 10;`,
  `Math.sqrt(49);`,
  `10 % 3;`,
  `(4 + 4) / 2;`,
  `20 - (5 + 5);`,
  `(3 * 3) + 2;`,
  `100 / 10;`,
  `8 * (2 + 1);`,
  `30 - (10 - 5);`,

  // Logic and booleans (61–80)

  `5 > 3;`,
  `2 < 1;`,
  `"a" === "a";`,
  `"hi" !== "bye";`,
  `[1,2].length === 2;`,
  `{{age}} > 18;`,
  `"dog".includes("d");`,
  `10 % 2 === 0;`,
  `[1,3,5].includes(2);`,
  `"blue".length > 3;`,
  `5 + 5 === 10;`,
  `9 - 4 === 5;`,
  `("hi" + "bye").length === 5;`,
  `true && false;`,
  `true || false;`,
  `!("hello".includes("z"));`,
  `5 * 2 === 10;`,
  `"sky"[1] === "k";`,
  `[1,2,3][0] === 1;`,
  `("ab".repeat(2)) === "abab";`,

  // Function evaluation (81–100)

  `function x(n){ return n * 2 } x(5);`,
  `function greet(n){ return "Hi " + n } greet("{{name}}");`,
  `function len(s){ return s.length } len("hello");`,
  `function first(a){ return a[0] } first(["a","b"]);`,
  `function last(a){ return a[a.length-1] } last([2,4,6]);`,
  `function add(a,b){ return a+b } add(3,7);`,
  `function loud(w){ return w.toUpperCase() } loud("yes");`,
  `function wrap(x){ return "["+x+"]" } wrap("ok");`,
  `function city(){ return "{{city}}" } city();`,
  `function isBig(n){ return n > 10 } isBig(12);`,
  `function double(n){ return n*2 } double(9);`,
  `function tag(t){ return t+"_tag" } tag("js");`,
  `function firstChar(s){ return s[0] } firstChar("test");`,
  `function area(a,b){ return a*b } area(4,5);`,
  `function rate(n){ return n/2 } rate(20);`,
  `function exclaim(w){ return w+"!" } exclaim("hi");`,
  `function id(x){ return x } id("done");`,
  `function middle(arr){ return arr[1] } middle([1,2,3]);`,
  `function agePlus(n){ return n+5 } agePlus({{age}});`,
  `function combo(a,b){ return a+" "+b } combo("hello","world");`,
];
