export const level45 = [
  // --- LEVEL 45: REDUCE — ACCUMULATING VALUES INTO ONE RESULT (1–100) ---

  // Basic numeric sums (1–20)

  `[1, 2, 3].reduce((total, n) => total + n, 0);`,
  `[5, 5].reduce((t, n) => t + n, 0);`,
  `[10, 20].reduce((sum, n) => sum + n, 0);`,
  `[2, 4, 6].reduce((x, y) => x + y, 0);`,
  `[9, 1].reduce((a, b) => a + b, 0);`,
  `[3, 3, 3].reduce((t, n) => t + n, 0);`,
  `[7, 14].reduce((s, n) => s + n, 0);`,
  `[1, 1, 1, 1].reduce((t, n) => t + n, 0);`,
  `[4, 5, 6].reduce((t, n) => t + n, 0);`,
  `[10, -5].reduce((t, n) => t + n, 0);`,
  `[100, 200].reduce((t, n) => t + n, 0);`,
  `[8, 8].reduce((t, n) => t + n, 0);`,
  `[12, 3].reduce((t, n) => t + n, 0);`,
  `[6, 7].reduce((t, n) => t + n, 0);`,
  `[1, 2, 1].reduce((t, n) => t + n, 0);`,
  `[9, 3].reduce((t, n) => t + n, 0);`,
  `[11, 9].reduce((t, n) => t + n, 0);`,
  `[2, 2, 2, 2].reduce((t, n) => t + n, 0);`,
  `[14, 1].reduce((t, n) => t + n, 0);`,
  `[3, 7].reduce((t, n) => t + n, 0);`,

  // Multiplying values (21–40)

  `[2, 2].reduce((p, n) => p * n, 1);`,
  `[3, 3].reduce((p, n) => p * n, 1);`,
  `[1, 2, 3].reduce((p, n) => p * n, 1);`,
  `[4, 5].reduce((p, n) => p * n, 1);`,
  `[6, 2].reduce((p, n) => p * n, 1);`,
  `[3, 1, 2].reduce((p, n) => p * n, 1);`,
  `[7, 1].reduce((p, n) => p * n, 1);`,
  `[2, 3, 4].reduce((p, n) => p * n, 1);`,
  `[5, 1].reduce((p, n) => p * n, 1);`,
  `[8, 1].reduce((p, n) => p * n, 1);`,
  `[2, 2, 2].reduce((p, n) => p * n, 1);`,
  `[9, 1].reduce((p, n) => p * n, 1);`,
  `[3, 4].reduce((p, n) => p * n, 1);`,
  `[10, 1].reduce((p, n) => p * n, 1);`,
  `[6, 3].reduce((p, n) => p * n, 1);`,
  `[2, 5].reduce((p, n) => p * n, 1);`,
  `[4, 4].reduce((p, n) => p * n, 1);`,
  `[1, 7].reduce((p, n) => p * n, 1);`,
  `[8, 2].reduce((p, n) => p * n, 1);`,
  `[9, 2].reduce((p, n) => p * n, 1);`,

  // String accumulation (41–60)

  `["a","b","c"].reduce((s, ch) => s + ch, "");`,
  `["hello","world"].reduce((s, w) => s + " " + w, "");`,
  `["{{name}}"].reduce((s, n) => "Hi " + n, "");`,
  `["JS","is","fun"].reduce((s, w) => s + "-" + w, "");`,
  `["A","B"].reduce((s, c) => s + c, "");`,
  `["code","more"].reduce((s, w) => s + "_" + w, "");`,
  `["red","blue"].reduce((s, c) => s + " " + c, "");`,
  `["sun","set"].reduce((s, part) => s + part, "");`,
  `["up","grade"].reduce((s, p) => s + p, "");`,
  `["{{city}}"].reduce((s, c) => "City: " + c, "");`,
  `["data","base"].reduce((s, p) => s + p, "");`,
  `["good","job"].reduce((s, p) => s + " " + p, "");`,
  `["learn","more"].reduce((s, w) => s + "_" + w, "");`,
  `["front","end"].reduce((s, p) => s + p, "");`,
  `["nice","work"].reduce((s, p) => s + "-" + p, "");`,
  `["code","block"].reduce((s, p) => s + " " + p, "");`,
  `["win","ner"].reduce((s, p) => s + p, "");`,
  `["day","light"].reduce((s, p) => s + p, "");`,
  `["stay","focused"].reduce((s, p) => s + " " + p, "");`,
  `["map","reduce"].reduce((s, p) => s + "-" + p, "");`,

  // Counting items manually (61–80)

  `[1,1,1].reduce((count) => count + 1, 0);`,
  `[2,4,6].reduce((count) => count + 1, 0);`,
  `["a","b"].reduce((count) => count + 1, 0);`,
  `["x","y","z"].reduce((count) => count + 1, 0);`,
  `[true,false].reduce((c) => c + 1, 0);`,
  `["{{name}}"].reduce((c) => c + 1, 0);`,
  `[10,20,30,40].reduce((c) => c + 1, 0);`,
  `[7].reduce((c) => c + 1, 0);`,
  `["hi","hey"].reduce((c) => c + 1, 0);`,
  `[null,"a"].reduce((c) => c + 1, 0);`,
  `[1,5,9].reduce((c) => c + 1, 0);`,
  `[true,true].reduce((c) => c + 1, 0);`,
  `[3,3,3].reduce((c) => c + 1, 0);`,
  `["long","short","mid"].reduce((c) => c + 1, 0);`,
  `["lake"].reduce((c) => c + 1, 0);`,
  `[0,0,0].reduce((c) => c + 1, 0);`,
  `["red","blue"].reduce((c) => c + 1, 0);`,
  `["sun","moon"].reduce((c) => c + 1, 0);`,
  `["a","b","c","d"].reduce((c) => c + 1, 0);`,
  `[9].reduce((c) => c + 1, 0);`,

  // Object-building reductions (81–100)

  `["red","blue"].reduce((obj, c) => ({ ...obj, color: c }), {});`,
  `["{{name}}"].reduce((o, n) => ({ name: n }), {});`,
  `["{{city}}"].reduce((o, c) => ({ city: c }), {});`,
  `[5].reduce((o, n) => ({ number: n }), {});`,
  `["A"].reduce((o, l) => ({ letter: l }), {});`,
  `["code"].reduce((o, w) => ({ word: w }), {});`,
  `["hello"].reduce((o, w) => ({ text: w }), {});`,
  `["JS"].reduce((o, v) => ({ lang: v }), {});`,
  `["cat"].reduce((o, p) => ({ pet: p }), {});`,
  `["green"].reduce((o, c) => ({ color: c }), {});`,
  `["lake"].reduce((o, w) => ({ water: w }), {});`,
  `["bike"].reduce((o, v) => ({ vehicle: v }), {});`,
  `["cup"].reduce((o, i) => ({ item: i }), {});`,
  `["wind"].reduce((o, v) => ({ air: v }), {});`,
  `["tree"].reduce((o, w) => ({ plant: w }), {});`,
  `["note"].reduce((o, t) => ({ text: t }), {});`,
  `["run"].reduce((o, v) => ({ action: v }), {});`,
  `["sun"].reduce((o, v) => ({ star: v }), {});`,
  `["road"].reduce((o, r) => ({ path: r }), {});`,
  `["stone"].reduce((o, s) => ({ rock: s }), {});`,
];
