export const level42 = [
  // --- LEVEL 42: INTRO TO .map() TRANSFORMATIONS (1–100) ---
  // Basic number transforms (1–20)

  `[1, 2, 3].map(n => n * 2);`,
  `[4, 5, 6].map(n => n + 1);`,
  `[2, 4, 6].map(n => n / 2);`,
  `[3, 6, 9].map(n => n - 1);`,
  `[10, 20].map(n => n * n);`,
  `[5, 10, 15].map(n => n / 5);`,
  `[1, 2, 3].map(n => n ** 2);`,
  `[7, 14].map(n => n / 7);`,
  `[8, 16].map(n => n / 8);`,
  `[3, 5].map(n => n * 3);`,
  `[2, 3, 4].map(n => n + 10);`,
  `[9, 18].map(n => n / 9);`,
  `[1, 4, 9].map(n => Math.sqrt(n));`,
  `[5, 10, 20].map(n => n - 5);`,
  `[3, 6, 12].map(n => n / 3);`,
  `[10, 30].map(n => n * 0.5);`,
  `[2, 8].map(n => n * 4);`,
  `[6, 12].map(n => n / 2);`,
  `[1, 5, 10].map(n => n + 2);`,
  `[4, 16].map(n => n ** 0.5);`,

  // String transforms — uppercase, lowercase, formatting (21–40)

  `["hi", "bye"].map(s => s.toUpperCase());`,
  `["CAT", "DOG"].map(s => s.toLowerCase());`,
  `["{{name}}", "Sam"].map(s => "Hello " + s);`,
  `["{{city}}", "Rome"].map(s => s + "!");`,
  `["apple", "pear"].map(s => s[0]);`,
  `["yes", "no"].map(s => s.length);`,
  `["red", "blue"].map(s => s + " color");`,
  `["car", "bus"].map(s => "Vehicle: " + s);`,
  `["one", "two"].map(s => s.repeat(2));`,
  `["{{country}}"].map(s => "From " + s);`,
  `["A", "B"].map(s => s + s);`,
  `["sun", "sky"].map(s => s.toUpperCase());`,
  `["phone", "tv"].map(s => s + " device");`,
  `["x", "y"].map(s => s + "-tag");`,
  `["alpha", "beta"].map(s => s.length + 1);`,
  `["hi", "hello"].map(s => s + " world");`,
  `["car", "bike"].map(s => s + " ride");`,
  `["rock", "tree"].map(s => s.slice(0, 2));`,
  `["JS", "Code"].map(s => s + " practice");`,
  `["{{job}}"].map(s => "Job: " + s);`,

  // Object transforms — extracting and formatting (41–60)

  `[{ age: 10 }, { age: 20 }].map(o => o.age);`,
  `[{ name: "{{name}}" }].map(o => "Name: " + o.name);`,
  `[{ city: "{{city}}" }, { city: "Paris" }].map(o => o.city.toUpperCase());`,
  `[{ score: 5 }, { score: 10 }].map(o => o.score * 2);`,
  `[{ x: 1 }, { x: 2 }].map(o => o.x + 5);`,
  `[{ age: {{age}} }].map(o => o.age - 2);`,
  `[{ value: 50 }, { value: 100 }].map(o => "Value " + o.value);`,
  `[{ n: 3 }, { n: 9 }].map(o => Math.sqrt(o.n));`,
  `[{ pet: "Dog" }, { pet: "Cat" }].map(o => o.pet.length);`,
  `[{ job: "{{job}}" }].map(o => o.job + " role");`,
  `[{ temp: 30 }, { temp: 15 }].map(o => o.temp + "°C");`,
  `[{ id: 1 }, { id: 2 }].map(o => o.id * 10);`,
  `[{ title: "Book" }].map(o => "Title: " + o.title);`,
  `[{ rooms: 3 }].map(o => o.rooms + 1);`,
  `[{ city: "Rome" }, { city: "{{city}}" }].map(o => o.city + " City");`,
  `[{ age: 18 }, { age: 25 }].map(o => o.age >= 18);`,
  `[{ brand: "BMW" }].map(o => o.brand.toUpperCase());`,
  `[{ country: "{{country}}" }].map(o => "Country: " + o.country);`,
  `[{ x: 10 }, { x: 20 }].map(o => o.x / 10);`,
  `[{ hero: "Flash" }].map(o => o.hero + "!");`,

  // Create new objects from old ones (61–80)

  `[{ name: "{{name}}", age: {{age}} }].map(o => ({ label: o.name }));`,
  `[{ city: "{{city}}", pop: 100 }].map(o => ({ place: o.city }));`,
  `[{ n: 5 }].map(o => ({ double: o.n * 2 }));`,
  `[{ a: 2 }, { a: 4 }].map(o => ({ squared: o.a ** 2 }));`,
  `[{ temp: 20 }].map(o => ({ celsius: o.temp }));`,
  `[{ car: "BMW" }].map(o => ({ brand: o.car }));`,
  `[{ job: "{{job}}" }].map(o => ({ role: o.job }));`,
  `[{ pet: "Dog" }].map(o => ({ animal: o.pet }));`,
  `[{ x: 1 }, { x: 2 }].map(o => ({ xTimesTen: o.x * 10 }));`,
  `[{ age: {{age}} }].map(o => ({ decade: Math.floor(o.age / 10) }));`,
  `[{ country: "{{country}}" }].map(o => ({ code: o.country.length }));`,
  `[{ hero: "Batman" }].map(o => ({ shout: o.hero + "!" }));`,
  `[{ fruit: "Apple" }].map(o => ({ first: o.fruit[0] }));`,
  `[{ number: 5 }].map(o => ({ minus: o.number - 1 }));`,
  `[{ value: 20 }].map(o => ({ triple: o.value * 3 }));`,
  `[{ flag: "Swiss" }].map(o => ({ lower: o.flag.toLowerCase() }));`,
  `[{ food: "Pizza" }].map(o => ({ length: o.food.length }));`,
  `[{ planet: "Earth" }].map(o => ({ tag: o.planet + "_planet" }));`,
  `[{ city: "{{city}}" }].map(o => ({ small: o.city.toLowerCase() }));`,
  `[{ name: "{{name}}" }].map(o => ({ initials: o.name[0] }));`,

  // Mixed map challenges (81–100)

  `[1, 2, 3].map(n => n + 2);`,
  `["hi", "yo"].map(s => s + "!");`,
  `[{ n: 10 }].map(o => o.n / 2);`,
  `["a", "b"].map(s => s.toUpperCase());`,
  `[3, 6, 9].map(n => n / 3);`,
  `["{{city}}"].map(s => s + " city");`,
  `[{ age: 5 }, { age: 10 }].map(o => o.age * 2);`,
  `[2, 4, 8].map(n => n ** 2);`,
  `["cat", "dog"].map(s => s.length);`,
  `[100, 50].map(n => n / 10);`,
  `["sun", "moon"].map(s => s.toUpperCase());`,
  `[{ job: "{{job}}" }].map(o => o.job + "!");`,
  `[5, 10].map(n => n - 3);`,
  `[{ city: "{{city}}" }].map(o => o.city.length);`,
  `[1, 5, 10].map(n => n * 5);`,
  `["A", "AA"].map(s => s.toLowerCase());`,
  `[{ value: 2 }].map(o => o.value + 7);`,
  `["{{country}}"].map(s => s + " Country");`,
  `[9, 18, 27].map(n => n / 9);`,
  `["ok"].map(s => s.toUpperCase());`,
];
