export const level44 = [
  // --- LEVEL 44: FILTER — SELECTING VALUES FROM ARRAYS (1–100) ---

  // Basic numeric filters (1–20)

  `[1, 2, 3, 4].filter(n => n > 2);`,
  `[5, 10, 15].filter(n => n < 10);`,
  `[2, 4, 6, 8].filter(n => n % 2 === 0);`,
  `[1, 3, 5, 7].filter(n => n > 4);`,
  `[10, 20, 30].filter(n => n !== 20);`,
  `[3, 6, 9].filter(n => n > 5);`,
  `[4, 8, 12].filter(n => n / 2 > 3);`,
  `[7, 14, 21].filter(n => n % 7 === 0);`,
  `[1, 5, 10].filter(n => n >= 5);`,
  `[9, 3, 1].filter(n => n < 4);`,
  `[2, 3, 4].filter(n => n === 3);`,
  `[10, 5, 0].filter(n => n <= 5);`,
  `[8, 12, 16].filter(n => n > 10);`,
  `[1, 4, 9].filter(n => n % 3 === 0);`,
  `[3, 3, 3].filter(n => n === 3);`,
  `[5, 15, 25].filter(n => n > 10);`,
  `[2, 7, 11].filter(n => n > 5);`,
  `[12, 18, 24].filter(n => n % 6 === 0);`,
  `[4, 5, 6].filter(n => n < 5);`,
  `[100, 200].filter(n => n === 200);`,

  // Filtering strings (21–40)

  `["a", "b", "c"].filter(l => l === "b");`,
  `["red","blue","green"].filter(c => c.length === 4);`,
  `["car","bike","bus"].filter(v => v[0] === "b");`,
  `["apple","banana","pear"].filter(f => f.includes("a"));`,
  `["dog","cat","bird"].filter(p => p.length > 3);`,
  `["sun","moon","star"].filter(w => w !== "moon");`,
  `["{{city}}","Paris","Rome"].filter(c => c !== "Rome");`,
  `["{{name}}","Alex","Sam"].filter(n => n.length > 3);`,
  `["cup","mug","glass"].filter(i => i.includes("g"));`,
  `["blue","yellow","pink"].filter(c => c[0] === "y");`,
  `["hi","hello","hey"].filter(w => w.length > 2);`,
  `["A","B","C"].filter(l => l !== "B");`,
  `["cat","cow","crow"].filter(a => a.includes("ow"));`,
  `["car","van","bus"].filter(v => v !== "van");`,
  `["phone","tablet","pc"].filter(d => d.length > 3);`,
  `["lake","river","sea"].filter(w => w.includes("e"));`,
  `["run","walk","jump"].filter(a => a !== "jump");`,
  `["ball","bat","glove"].filter(i => i.length === 4);`,
  `["cold","warm","hot"].filter(t => t.length > 3);`,
  `["pen","pencil","marker"].filter(i => i.includes("n"));`,

  // Filtering mixed values (41–60)

  `[1, "2", 3].filter(v => typeof v === "number");`,
  `["7", 7, "eight"].filter(v => typeof v === "string");`,
  `["yes", true, "no"].filter(v => typeof v === "string");`,
  `[true, false, true].filter(b => b === true);`,
  `[0, 1, 2, 3].filter(n => n % 2 === 1);`,
  `["{{country}}", 10, null].filter(v => typeof v === "string");`,
  `[null, "a", undefined].filter(v => v === "a");`,
  `[false, "false", 0].filter(v => !v);`,
  `[1, 2, "3"].filter(v => v != "3");`,
  `["one", 1, 2].filter(v => typeof v === "number");`,
  `["dog", 3, "cat"].filter(v => typeof v === "string");`,
  `[10, "10", 20].filter(v => typeof v === "number");`,
  `[true, "true", false].filter(v => v === false);`,
  `[4, "4", 5].filter(v => v === 4);`,
  `["code", 100, "js"].filter(v => typeof v === "string");`,
  `[null, 0, "0"].filter(v => v === 0);`,
  `["hi", undefined, "hello"].filter(v => typeof v === "string");`,
  `[1, 3, 5, 6].filter(n => n < 5);`,
  `["long","short"].filter(w => w.length > 4);`,
  `[true, false].filter(b => b);`,

  // Filtering with logical conditions (61–80)

  `[5, 10, 15].filter(n => n > 5 && n < 15);`,
  `[1, 2, 3, 4].filter(n => n !== 2 && n !== 3);`,
  `[7, 14, 21].filter(n => n % 7 === 0 && n > 10);`,
  `[3, 6, 9].filter(n => n >= 6);`,
  `["cat","cow","crow"].filter(w => w.includes("c"));`,
  `["apple","pear","plum"].filter(f => f.includes("p"));`,
  `["sun","sand","sea"].filter(w => w[0] === "s");`,
  `["Paris","London","{{city}}"].filter(c => c.length > 5);`,
  `["blue","green","red"].filter(c => c !== "red");`,
  `[2,4,6,7].filter(n => n % 2 === 0);`,
  `["{{name}}","Ana","Jon"].filter(n => n.length > 2);`,
  `[10, 20, 30, 40].filter(n => n <= 20);`,
  `[5, 8, 12].filter(n => n > 6 && n < 12);`,
  `["warm","cold","hot"].filter(t => t.includes("o"));`,
  `["tree","bush","leaf"].filter(w => w.length >= 4);`,
  `[1, 9, 3].filter(n => n > 2 && n !== 9);`,
  `["hi","hey","hello"].filter(w => w.length === 3);`,
  `[100, 200, 300].filter(n => n !== 200);`,
  `["cat","bat","rat"].filter(w => w !== "bat");`,
  `[true,false,true].filter(b => b === true);`,

  // More advanced filtering patterns (81–100)

  `[1,2,3,4,5].filter(n => n > 3);`,
  `["a","ab","abc"].filter(w => w.length > 1);`,
  `["red","blue","green"].filter(c => c.includes("e"));`,
  `["car","bike","boat"].filter(v => v[0] === "b");`,
  `[10,5,0,-5].filter(n => n >= 0);`,
  `[2,3,4,5].filter(n => n % 2 === 1);`,
  `["apple","banana"].filter(f => f !== "banana");`,
  `["JS","HTML","CSS"].filter(t => t.length === 2);`,
  `["run","jump","walk"].filter(w => w.includes("a"));`,
  `[7,14,28].filter(n => n > 10);`,
  `[1,4,9,16].filter(n => n < 10);`,
  `["short","long"].filter(w => w.length > 4);`,
  `[true,false,false].filter(b => b === false);`,
  `[2,4,6,8].filter(n => n > 4);`,
  `["bird","cat","dog"].filter(w => w !== "cat");`,
  `[10,20,30].filter(n => n === 20);`,
  `["yes","no"].filter(w => w === "yes");`,
  `[1,2,"2"].filter(v => typeof v === "number");`,
  `["{{country}}","USA"].filter(c => c !== "USA");`,
  `["home","house"].filter(w => w.includes("o"));`,
];
